name: CentOS Base Image
on:
  schedule:
  - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Running Build
       run: |
         docker build -t ghcr.io/itechpros/centos:7 centos-base
     - name: Uploading Image
       run: |
         docker push ghcr.io/itechpros/centos:7
