name: Developer Builds
on:
  push:
    branches:
     - main
  workflow_call:
jobs:
  build-servoy-6:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [{build: 1439, name: 6.1.6}, {build: 1433, name: 6.1.5}, {build: 1429, name: 6.1.4}, {build: 1424, name: 6.1.3}, {build: 1421, name: 6.1.2}, {build: 1420, name: 6.1.1}, {build: 1418, name: 6.1.0}]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Create OpenJDK 8 base image
       run: |
         docker build -t itechpros/openjdk:8 openjdk-8-base
     - name: 25 Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar
  build-servoy-7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [{build: 2049, name: 7.4.10}, {build: 2047, name: 7.4.9}, {build: 2046, name: 7.4.8}, {build: 2045, name: 7.4.7}, {build: 2043, name: 7.4.6}, {build: 2041, name: 7.4.5}, {build: 2039, name: 7.4.4}, {build: 2036, name: 7.4.3}, {build: 2033, name: 7.4.2}, {build: 2028, name: 7.4.1}, {build: 2026, name: 7.4.0}, {build: 2022, name: 7.3.1}, {build: 2018, name: 7.3.0}, {build: 2013, name: 7.2.0}]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Create OpenJDK 8 base image
       run: |
         docker build -t itechpros/openjdk:8 openjdk-8-base
     - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=7 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar
  build-servoy-8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [{build: 3401, name: 8.4.0}, {build: 3208, name: 8.3.3}, {build: 3206, name: 8.3.2}, {build: 3204, name: 8.3.1}, {build: 3108, name: 8.2.3}, {build: 3106, name: 8.2.2}, {build: 3104, name: 8.2.1}, {build: 3102, name: 8.2.0}, {build: 3034, name: 8.1.4}, {build: 3032, name: 8.1.3}, {build: 3030, name: 8.1.2}, {build: 3028, name: 8.1.1}, {build: 3026, name: 8.1.0}, {build: 3019, name: 8.0.0}]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Create OpenJDK 8 base image
       run: |
         docker build -t itechpros/openjdk:8 openjdk-8-base
     - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar
  # build-servoy-2020:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
  # build-servoy-2021:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
  # build-servoy-2022:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
