name: Developer Builds
on:
  push:
    branches:
     - main
  workflow_call:
jobs:
  build-servoy-6:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Build Servoy 6.1.6 (1439) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.6.1439-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1439 developer-base-jar
     - name: Build Servoy 6.1.5 (1433) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.5.1433-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1433 developer-base-jar
     - name: Build Servoy 6.1.4 (1429) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.4.1429-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1429 developer-base-jar
     - name: Build Servoy 6.1.3 (1424) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.3.1424-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1424 developer-base-jar
     - name: Build Servoy 6.1.2 (1421) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.2.1421-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1421 developer-base-jar
     - name: Build Servoy 6.1.1 (1420) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.2.1420-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1420 developer-base-jar
     - name: Build Servoy 6.1.0 (1418) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.1.0.1418-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1418 developer-base-jar
     - name: Build Servoy 6.0.11 (1241) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.0.11.1241-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1241 developer-base-jar
     - name: Build Servoy 6.0.10 (1240) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.0.10.1240-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1240 developer-base-jar
     - name: Build Servoy 6.0.9 (1239) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.0.9.1239-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1239 developer-base-jar
     - name: Build Servoy 6.0.8 (1237) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.0.8.1237-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1237 developer-base-jar
     - name: Build Servoy 6.0.7 (1235) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:6.0.7.1235-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=1235 developer-base-jar
  # build-servoy-7:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
  # build-servoy-8:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
  # build-servoy-2020:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
  # build-servoy-2021:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
  # build-servoy-2022:
  #   runs-on: ubuntu-latest
  #   needs: authenticate
  #   steps:
  #    - name: Test
  #      run: |
  #        echo Hello world!
