name: Developer Builds
on:
  # push:
  #   branches:
  #    - main
  workflow_call:
jobs:
  build-servoy-6:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [{build: 1439, name: 6.1.6}, {build: 1433, name: 6.1.5}, {build: 1429, name: 6.1.4}, {build: 1424, name: 6.1.3}, {build: 1421, name: 6.1.2}, {build: 1420, name: 6.1.1}, {build: 1418, name: 6.1.0}]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Create OpenJDK 8 base image
       run: |
         docker build -t itechpros/openjdk:8 openjdk-8-base
     - name: 25 Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=6 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar
  build-servoy-7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [{build: 2049, name: 7.4.10}, {build: 2047, name: 7.4.9}, {build: 2046, name: 7.4.8}, {build: 2045, name: 7.4.7}, {build: 2043, name: 7.4.6}, {build: 2041, name: 7.4.5}, {build: 2039, name: 7.4.4}, {build: 2036, name: 7.4.3}, {build: 2033, name: 7.4.2}, {build: 2028, name: 7.4.1}, {build: 2026, name: 7.4.0}, {build: 2022, name: 7.3.1}, {build: 2018, name: 7.3.0}, {build: 2013, name: 7.2.0}]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Create OpenJDK 8 base image
       run: |
         docker build -t itechpros/openjdk:8 openjdk-8-base
     - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=7 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar
  build-servoy-8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [{build: 3402, name: 8.4.0}, {build: 3209, name: 8.3.3}, {build: 3207, name: 8.3.2}, {build: 3205, name: 8.3.1}, {build: 3109, name: 8.2.3}, {build: 3107, name: 8.2.2}, {build: 3105, name: 8.2.1}, {build: 3103, name: 8.2.0}, {build: 3035, name: 8.1.4}, {build: 3033, name: 8.1.3}, {build: 3031, name: 8.1.2}, {build: 3029, name: 8.1.1}, {build: 3027, name: 8.1.0}, {build: 3020, name: 8.0.0}]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Create OpenJDK 8 base image
       run: |
         docker build -t itechpros/openjdk:8 openjdk-8-base
     - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
       run: |
         docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar
  # build-servoy-2019-jar:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: [{build: 3413, name: 2019.03.1}, {build: 3412, name: 2019.03}]
  #   steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Docker Login
  #      uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Create OpenJDK 8 base image
  #      run: |
  #        docker build -t itechpros/openjdk:8 openjdk-8-base
  #    - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
  #      run: |
  #        docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}}-jdk8 --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-jar 
  # build-servoy-2019-zip:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: [{build: 3543, name: 2019.12.1}, {build: 3542, name: 2019.12}, {build: 3522, name: 2019.09}, {build: 3504, name: 2019.06.2}, {build: 3503, name: 2019.06.1}, {build: 3502, name: 2019.06}, {build: 3414, name: 2019.03.2}]
  #   steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Docker Login
  #      uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
  #      run: |
  #        docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}} --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-targz 
  # build-servoy-2020:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: [{build: 3623, name: 2020.12.1}, {build: 3622, name: 2020.12}, {build: 3602, name: 2020.09}, {build: 3583, name: 2020.06.1}, {build: 3582, name: 2020.06}, {build: 3565, name: 2020.03.3}, {build: 3564, name: 2020.03.2}, {build: 3563, name: 2020.03.1}, {build: 3562, name: 2020.03}]
  #   steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Docker Login
  #      uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
  #      run: |
  #        docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}} --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-targz 
  # build-servoy-2021:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: [{build: 3724, name: 2021.12.2}, {build: 3723, name: 2021.12.1}, {build: 3722, name: 2021.12}, {build: 3703, name: 2021.09}, {build: 3683, name: 2021.06}, {build: 3645, name: 2021.03.3}, {build: 3644, name: 2021.03.2}, {build: 3643, name: 2021.03.1}, {build: 3642, name: 2021.03}]
  #   steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Docker Login
  #      uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
  #      run: |
  #        docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}} --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-targz 
  # build-servoy-2022:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: [{build: 3782, name: 2022.06}, {build: 3744, name: 2022.03.2}, {build: 3743, name: 2022.03.1}, {build: 3742, name: 2022.03}]
  #   steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Docker Login
  #      uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Build Servoy ${{matrix.version.name}} (${{matrix.version.build}}) images
  #      run: |
  #        docker build -t ghcr.io/itechpros/servoy_installer:${{matrix.version.name}}.${{matrix.version.build}} --build-arg SERVOY_VERSION_MAJOR=8 --build-arg SERVOY_VERSION_BUILD=${{matrix.version.build}} developer-base-targz 
