name: Developer Builds
on:
  push:
    branches:
     - main
  workflow_call:
jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Login
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  build-servoy-6:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
     - name: Test
       run: |
         echo Hello world!
  build-servoy-7:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
     - name: Test
       run: |
         echo Hello world!
  build-servoy-8:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
     - name: Test
       run: |
         echo Hello world!
  build-servoy-2020:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
     - name: Test
       run: |
         echo Hello world!
  build-servoy-2021:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
     - name: Test
       run: |
         echo Hello world!
  build-servoy-2022:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
     - name: Test
       run: |
         echo Hello world!
